name: Rancher `scc-operator` CI

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'

permissions:
  contents: read

jobs:
  build:
    name : Build, test  & validate
    runs-on : ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/go1.26
    strategy:
      matrix:
          include:
            - platform: linux/amd64
            - platform: linux/arm64
    steps:
      - name : Checkout repository
        uses : actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Cache Go modules and build cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.platform }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.platform }}-
            ${{ runner.os }}-go-

      - name : CI
        run : CI=true make ci
